//! Export the canonical schema + migrations as a TypeScript module for the
//! mobile app. Run from the repo:
//!
//! ```sh
//! cargo run -p cordanui-schema --example export_ts
//! ```
//!
//! Writes `mobile/src/db/schema.generated.ts`. The file is committed, so
//! mobile builds never need the Rust toolchain — but a drift test in this
//! crate fails if the generated file falls out of sync with the source of
//! truth.

use cordanui_schema::{MIGRATIONS, SCHEMA_SQL};

fn generated_ts() -> String {
    let mut out = String::new();
    out.push_str(
        "// AUTO-GENERATED by `cargo run -p cordanui-schema --example export_ts`.\n\
         // Source of truth: rust/schema/schema.sql + crates/schema MIGRATIONS.\n\
         // Do not edit by hand — regenerate instead.\n\n",
    );

    out.push_str("export const SCHEMA_SQL = ");
    out.push_str(&serde_json::to_string(SCHEMA_SQL).expect("schema sql serializes"));
    out.push_str(";\n\n");

    let latest = MIGRATIONS.iter().map(|m| m.version).max().unwrap_or(0);
    out.push_str(&format!(
        "export const LATEST_SCHEMA_VERSION = {latest};\n\n"
    ));

    out.push_str("export interface SharedMigration {\n  version: number;\n  name: string;\n  sql: string;\n}\n\n");
    out.push_str("export const SHARED_MIGRATIONS: SharedMigration[] = ");
    let migrations: Vec<serde_json::Value> = MIGRATIONS
        .iter()
        .map(|m| {
            serde_json::json!({
                "version": m.version,
                "name": m.name,
                "sql": m.sql,
            })
        })
        .collect();
    out.push_str(&serde_json::to_string_pretty(&migrations).expect("migrations serialize"));
    out.push_str(";\n");
    out
}

fn target_path() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../../mobile/src/db/schema.generated.ts")
}

fn main() -> anyhow::Result<()> {
    let contents = generated_ts();
    let path = target_path();
    std::fs::create_dir_all(path.parent().unwrap())?;
    std::fs::write(&path, contents)?;
    println!("wrote {}", path.display());
    Ok(())
}
