[package]
name = "cordanui-sync"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cordanui-schema = { path = "../schema" }
anyhow = { workspace = true }
tracing = { workspace = true }
toml = { workspace = true }
dirs = { workspace = true }
rusqlite = { version = "0.32", features = ["bundled"] }
reqwest = { workspace = true, features = ["blocking", "json"] }
serde_json.workspace = true

[dev-dependencies]
rusqlite = { workspace = true, features = ["bundled"] }
